### ISSUE TITLE
Not clear that this provides consistent security

### ISSUE THREAD

**Issue by TotallyInformation** [cuongquay/node-red-contrib-websocket-auth0#3]
Am I right in thinking that this only checks for the token on startup?

As far as I am aware, once the connection has upgraded to ws(s), you can no longer send headers (it isn't part of the spec). That means that you can only check the authorisation header at the start. After that, there are no ongoing checks that the token is still valid. 

That would mean that you cannot timeout the token (JWT authorisation is meant to be short-lived due to the token hijack issue unless you put additional checks on the server) nor can you check whether the token is still coming from that actual originator.

While I'm not an expert by any means, this looks as though this node provides "security theatre" only and should not be relied upon for anything actually secure.

Please correct me if I'm wrong, I'd be happy to delete this if so.

**Comment by cuongquay** [comment]
You are right at that point but in general a websocket is a session base data transfering and every session is protected by its entry. You passed the door and do your right until you will be kicked out or you get it out. A session period should be smaller than an hour.

**Comment by TotallyInformation** [comment]
> You passed the door and do your right until you will be kicked out or you get it out. A session period should be smaller than an hour.

That is the point I was trying to make. The node proports to be a security feature but cannot provide session management since the only interaction is a the start (or possibly on a page reload).

Nor is there any mechanism to extend/update the session.

So the behaviour of AUTH0 on websockets is fundamentally different to the behaviour with http and does not enable the same amount of security.

I think that this needs to be indicated to the users in the README and/or help information otherwise people will be thinking that their websockets sessions are secure when potentially they are not.

**Comment by cuongquay** [comment]
"That is the point I was trying to make. The node proports to be a security feature but cannot provide session management since the only interaction is a the start (or possibly on a page reload)."

I dont think this argument is true. In somewhat usecase a start or reload of a node-red client is a start of session (sock upgraded) and inside that session is protected. Why it's not secured?

**Comment by TotallyInformation** [comment]
> I dont think this argument is true. In somewhat usecase a start or reload of a node-red client is a start of session (sock upgraded) and inside that session is protected. Why it's not secured?

Because JWT's are meant to be short lived to protect from hijack attacks against which they have no protection unless there is something validating a session at the server end. Those session checks have to happen often enough - e.g. within the session timeout. When working with an SPA, it is typical for the client _not_ to be reloaded very often. But websocket comms will usually happen more often. 

Because websocket connections can only carry a custom header on initial connection (once upgraded no custom headers are exchanged), only the websocket msgs themselves can carry the JWT back to the server for ongoing validation.

If you don't do regular validation of the JWT, you don't know whether the comms are coming from an authorised client or not.

**Comment by cuongquay** [comment]
In my imagination, the handshake protocol looks like this:
1. Client opens a TCP socket
2. Server accepts this TCP connection
3. Client send Websocket header with JWT token
4. Server check whether token is valid, then upgrade the TCP to be a websocket tunnel.
5. From now, client will exchange information with server on a validated TCP connection (tunnel).
...this connection is encrypted or not, by wss:// or ws://
6. From time to time... By a substainable reason, client keeps this connection long enough to pass over JWT timeout. Ex: over 1 hour, 7 days or a month.
7. Server is still accept the exchange because the connection wasnt dropped.
8. Client sends some data that shouldnt be authorized due to its token has been expired. But because they are still living in the room therefore they are authorized. => is this your point?

Regards,

**Comment by TotallyInformation** [comment]
> Client opens a TCP socket
> Server accepts this TCP connection
>Client send Websocket header with JWT token

I don't think that is correct.

The server generates the JWT and sends it to the client in the authorization header of the response. The client must then include that same header in every HTTPS request.

The problem is that you generally only get a single HTTPS request for a new websocket connection. It then "upgrades" to `wss` and the extra headers cannot be included.

> From time to time... By a substainable reason, client keeps this connection long enough to pass over JWT timeout. Ex: over 1 hour, 7 days or a month.

This is a problem. Tokens are NOT a security feature - they are a convenience feature. Tokens in themselves carry very little meaning typically and if the server isn't constantly validating where they came from, if hijacked (not that hard to achieve either by interception, log file exfiltration or via client-side malware), the server will merrily accept data from an attacker not just the valid client.

JWT's lifespan is meant to be minutes, hours at the most. Not days/weeks. The longer you keep them alive, the greater the risk that you will be getting and responding to requests from a hijacked session.

Put another way, JWT's do not provide _any_ session management. If your server isn't receiving the JWT regularly (seconds to minutes at most) **AND** validating that the data with the token aren't coming from the same authenticated client, you have a problem.

> Client sends some data that shouldnt be authorized due to its token has been expired. But because they are still living in the room therefore they are authorized. => is this your point?

Well, there are two points really.

1) How do you know that the data is coming from the client that originally authenticated?

2) If the server isn't receiving the JWT from the client on a regular basis, there is no way for the server to refresh it. Indeed, the _only_ way would be for the user to reload the client because, as you've said, that is generally the only time that the client will go back to an HTTPS connection and therefore will send the JWT again.

   Without that, the client can send data over websockets forever since the server isn't even able to check the JWT let alone handle issue 1.

**Comment by TotallyInformation** [comment]
Oh, and if the client isn't using a TLS secured connection, the initial token exchange is even easier to intercept and to hijack the token.

**Comment by TotallyInformation** [comment]
BTW, apologies for labouring these points. Part of it is for me to get a better understanding of what is going on when trying to secure Node-RED - something that I'm wrangling with for the uibuilder node. And to get another developers viewpoint. So thanks for your patience.

https://www.startpage.com/sp/search?q=the%20problem%20with%20JWT
https://developer.okta.com/blog/2017/08/17/why-jwts-suck-as-session-tokens

**Comment by TotallyInformation** [comment]
One further point. You can include the JWT in the query string for the websocket connection so that it _is_ exchanged each time. The issue with that is that it exposes the JWT to interception via intermediate proxies/caches and to server/proxy logs. Hence making the hijack issue even worse.

For uibuilder, I'm planning to have a standard data schema for the exchange of authentication data including the JWT in the body of every msg exchange. That deals with the immediate timing and proxy hijack issues. 

The security feature will also refuse to work for production use unless you have TLS security turned on - which further helps with the hijack issues.

It will then also provide a middleware feature with a simple templated example as default. This will let flow creators write their own user authentication **and** session management. It will also let them add extra metadata to the auth object on the msg so that things like authorisation, session expiry, etc can be sent back to the client.

**Comment by cuongquay** [comment]
> One further point. You can include the JWT in the query string for the websocket connection so that it _is_ exchanged each time. The issue with that is that it exposes the JWT to interception via intermediate proxies/caches and to server/proxy logs. Hence making the hijack issue even worse.
> 
> For uibuilder, I'm planning to have a standard data schema for the exchange of authentication data including the JWT in the body of every msg exchange. That deals with the immediate timing and proxy hijack issues.
> 
> The security feature will also refuse to work for production use unless you have TLS security turned on - which further helps with the hijack issues.
> 
> It will then also provide a middleware feature with a simple templated example as default. This will let flow creators write their own user authentication **and** session management. It will also let them add extra metadata to the auth object on the msg so that things like authorisation, session expiry, etc can be sent back to the client.

I think you started to get my point on the way a (web)-socket works! I dont want to talk about hịacking or MITM attack because of it's covered by the other layers/concept of the whole application.

And absolutely, if you want to have a higher content data security policy, you must build it by your own. A framework-like will offer you a gate to check the pass of a passenger. On the train, if you want to have a ticket controller to verify passenger's ticket quite often, that is your own solution. The gate is built to guarantee who has passed in hold a valid ticket until he is out of the other gate during a determined time frame. If there will be some issue that stop the train in a while, passengers can still get out of the platform without any penalty. 

Best Regards,
